version: '3.1'
services:

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'library'
      volumes:
        - ./data:/docker-entrypoint-initdb.d
      ports:
        - '5432:5432'