version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library

    ports:
      - "5432:5432"
    volumes:
        - ./data:/docker-entrypoint-initdb.d
